### ISSUE TITLE
init失败

### ISSUE THREAD

**Issue by mysteryzzp** [fuxiaohei/pugo#1]
2023/05/06 14:52:24     INFO    PuGo 0.1.18
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\404.html', open default\404.html: file does not exist
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\archives.html', open default\archives.html: file does not exist
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\footer.html', open default\footer.html: file does not exist
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\head.html', open default\head.html: file does not exist
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\header.html', open default\header.html: file does not exist
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\page.html', open default\page.html: file does not exist
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\post-list.html', open default\post-list.html: file does not exist
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\post.html', open default\post.html: file does not exist
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\tailwind.config.js', open default\tailwind.config.js: file does not exist
2023/05/06 14:52:24     WARN    failed to extract theme file: 'default\theme_config.toml', open default\theme_config.toml: file does not exist
2023/05/06 14:52:24     INFO    initialized sample site in the current directory successfully

**Comment by fuxiaohei** [comment]
It seems windows compatible problems. This pr https://github.com/fuxiaohei/pugo/pull/3 is a fix ?

**Comment by mysteryzzp** [comment]
https://github.com/fuxiaohei/pugo/pull/3/commits/7f293f1913f2a9bcf96a325aa621433172c08f0e

读embed内容只能使用 /  不用能 \
